name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run linter
      uses: nebularg/actions-luacheck@v1.1.0
      with:
        files: "src/*.lua"
        args: "--no-color -q"
